Algoritmo "glicose"


Var
   glicose : real



Inicio
      escreva("Digite a medida da glicose: ")
      leia(glicose)
      
      se glicose <= 100.0 entao
         escreval ("Classificacao: normal ")
      senao
           se glicose <= 140.0 entao
              escreval("Classificacao: elevada ")
           senao
                escreval("Classificacao: diabete ")
           fimse
      fimse



Fimalgoritmo